repository:
  meta:
    patterns:
      - name: meta.attribute.saturnus
        begin: "#\\!?\\["
        end: \]
      - name: meta.statement.while-let.saturnus
        match: (while) (let)
        captures:
          "1":
            name: keyword.control.saturnus
          "2":
            name: storage.type.saturnus
      - name: meta.statement.if-let.saturnus
        match: (if) (let)
        captures:
          "1":
            name: keyword.control.saturnus
          "2":
            name: storage.type.saturnus
