repository:
  meta:
    patterns:
      - name: meta.decorator.saturnus
        match: "(#\\[[^\\[]\\])"
        captures:
          "1":
            name: keyword.decorator.saturnus
      - name: meta.decorator.saturnus
        match: "(@[A-Za-z_]+([A-Za-z_]|::)*)(?<![(])"
        captures:
          "1":
            name: keyword.decorator.saturnus
      - name: meta.statement.while-let.saturnus
        match: (while) (let)
        captures:
          "1":
            name: keyword.control.saturnus
          "2":
            name: storage.type.saturnus
      - name: meta.statement.if-let.saturnus
        match: (if) (let)
        captures:
          "1":
            name: keyword.control.saturnus
          "2":
            name: storage.type.saturnus
